apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi-prod
  labels:
    app: glpi-prod
spec:
  replicas: 1
  # --- ESTO ES LO QUE FALTABA ---
  selector:
    matchLabels:
      app: glpi-prod
  # ------------------------------
  template:
    metadata:
      labels:
        app: glpi-prod
    spec:
      containers:
      - name: glpi-container
        image: glpi:11.0.4
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
